package org.regitiny.minhshop;

import javax.annotation.Generated;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Generated(value = "JHipster", comments = "Generated by JHipster 7.0.0-beta.1")
@Retention(RetentionPolicy.SOURCE)
@Target({ElementType.TYPE})
public @interface GeneratedByJHipster
{
}
